export declare const DEFAULT_DAY_NAME_MARGIN_LEFT = "0";
export declare const MONTH_DAY_NAME_HEIGHT = 31;
export declare const MONTH_EVENT_BORDER_RADIUS = 2;
export declare const MONTH_EVENT_HEIGHT = 24;
export declare const MONTH_EVENT_MARGIN_TOP = 2;
export declare const MONTH_EVENT_MARGIN_LEFT = 8;
export declare const MONTH_EVENT_MARGIN_RIGHT = 8;
export declare const MONTH_CELL_PADDING_TOP = 3;
export declare const MONTH_CELL_BAR_HEIGHT = 27;
export declare const MONTH_MORE_VIEW_PADDING = 5;
export declare const MONTH_MORE_VIEW_MIN_WIDTH = 280;
export declare const MONTH_MORE_VIEW_HEADER_HEIGHT = 44;
export declare const MONTH_MORE_VIEW_HEADER_MARGIN_BOTTOM = 12;
export declare const MONTH_MORE_VIEW_HEADER_PADDING_TOP = 12;
export declare const MONTH_MORE_VIEW_HEADER_PADDING = "12px 17px 0";
export declare const WEEK_DAY_NAME_HEIGHT = 42;
export declare const WEEK_DAY_NAME_BORDER = 1;
export declare const WEEK_PANEL_RESIZER_HEIGHT = 3;
export declare const WEEK_EVENT_BORDER_RADIUS = 2;
export declare const WEEK_EVENT_HEIGHT = 24;
export declare const WEEK_EVENT_MARGIN_TOP = 2;
export declare const WEEK_EVENT_MARGIN_LEFT = 8;
export declare const WEEK_EVENT_MARGIN_RIGHT = 8;
export declare const DEFAULT_PANEL_HEIGHT = 52;
export declare const DEFAULT_EVENT_COLORS: {
    color: string;
    backgroundColor: string;
    dragBackgroundColor: string;
    borderColor: string;
};
export declare const TIME_EVENT_CONTAINER_MARGIN_LEFT = 2;
export declare const COLLAPSED_DUPLICATE_EVENT_WIDTH_PX = 9;
